version: '3.1'

services:
  kstb-bot:
    depends_on:
      - kstb-db
    build:
      context: .
    environment:
      BOT_NAME: 'KTITS_TIMETABLE_BOT'
      BOT_TOKEN: '5180815459:AAH3izIYRWGFYfCh9CttU86VewweI_GXgIs'
      BOT_DB_USERNAME: 'prod_kstb_db_user'
      BOT_DB_PASSWORD: 'prod_kstb_db_password'
    restart: always
  kstb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'prod_kstb_db_user'
      MYSQL_PASSWORD: 'prod_kstb_db_password'
      MYSQL_DATABASE: 'prod_kstb_db'
      MYSQL_ROOT_PASSWORD: '0520'
    ports:
      - '3308:3306'
    expose:
      - '3308'