version: '3.8'

services:
  kstb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_kstb_db'
      MYSQL_USER: 'dev_kstb_db_user'
      MYSQL_PASSWORD: 'dev_kstb_db_password'
      MYSQL_ROOT_PASSWORD: '0520'
    ports:
      - "3308:3306"
    expose:
      - '3308'