version: '3.1'

services:
  kstb-bot:
    depends_on:
      - kstb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  kstb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'kstb_db'
      MYSQL_ROOT_PASSWORD: 'kstb'
    ports:
        - '3308:3306'
    expose:
        - '3308'