version: '3.1'

services:
  kstb-bot:
    depends_on:
      - kstb-db
    build:
      context: .
    environment:
      BOT_NAME: 'ffff50505050_bot'
      BOT_TOKEN: '5240809296:AAG_JDxNL67GI4xYnNWt-_agGgJnILnSQC4'
      BOT_DB_USERNAME: 'prod_kstb_db_user'
      BOT_DB_PASSWORD: 'prod_kstb_db_password'
    restart: always
  kstb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'prod_kstb_db_user'
      MYSQL_PASSWORD: 'prod_kstb_db_password'
      MYSQL_DATABASE: 'prod_kstb_db'
      MYSQL_ROOT_PASSWORD: '0520'
    ports:
      - '3308:3306'
    expose:
      - '3308'